import { api } from '../api';
import { Card, ErrorBox, fmt, Loading } from '../components/ui';
import { useAsync, useInterval } from '../hooks';

function Health({ ok, label, detail }: { ok: boolean; label: string; detail?: string }) {
  return (
    <div className="kpi">
      <div className="k-label">{label}</div>
      <div className="row" style={{ marginTop: 6 }}>
        <span className={`badge ${ok ? 'good' : 'bad'}`}>
          <span className="dot" />
          {ok ? 'Connected' : 'Unavailable'}
        </span>
      </div>
      {detail && <div className="k-sub" style={{ marginTop: 6 }}>{detail}</div>}
    </div>
  );
}

export function SystemPage() {
  const { data, error, loading, reload } = useAsync(() => api.system(), []);
  useInterval(() => void reload(), 3000);

  return (
    <div className="page">
      <div className="page-header">
        <div>
          <h1>Workers &amp; system</h1>
          <div className="sub muted">
            {data?.mode === 'memory'
              ? 'In-memory mode: this server queues and runs every virtual user itself.'
              : 'Load is generated by workers that consume virtual-user jobs from RabbitMQ and report metrics to Redis.'}
          </div>
        </div>
      </div>
      {error && <ErrorBox error={error} retry={reload} />}
      {loading && !data ? (
        <Loading />
      ) : (
        data && (
          <div className="stack">
            <div className="kpis">
              <div className="kpi">
                <div className="k-label">Mode</div>
                <div className="k-value" style={{ fontSize: 20 }}>{data.mode === 'memory' ? 'In-memory' : 'Distributed'}</div>
                <div className="k-sub">{data.mode === 'memory' ? 'single process, no Redis/RabbitMQ' : 'RabbitMQ + Redis + worker fleet'}</div>
              </div>
              {data.mode === 'distributed' && (
                <>
                  <Health ok={data.redis.ok} label="Redis (state & metrics)" />
                  <Health
                    ok={data.rabbitmq.ok}
                    label="RabbitMQ (job queue)"
                    detail={data.rabbitmq.ok ? `${data.rabbitmq.messages} queued VU jobs · ${data.rabbitmq.consumers} consumers` : data.rabbitmq.error}
                  />
                </>
              )}
              <div className="kpi">
                <div className="k-label">Workers</div>
                <div className="k-value">{data.workers.length}</div>
                <div className="k-sub">live heartbeats</div>
              </div>
              <div className="kpi">
                <div className="k-label">Total capacity</div>
                <div className="k-value">{fmt.num(data.capacity)}</div>
                <div className="k-sub">concurrent virtual users</div>
              </div>
            </div>

            <Card bodyless title="Workers">
              {data.workers.length ? (
                <div className="table-wrap">
                  <table className="t">
                    <thead>
                      <tr>
                        <th>Worker</th>
                        <th>Type</th>
                        <th>Host</th>
                        <th>Broker</th>
                        <th className="r">Active VUs</th>
                        <th className="r">Capacity</th>
                        <th>Utilisation</th>
                        <th>Last heartbeat</th>
                      </tr>
                    </thead>
                    <tbody>
                      {data.workers.map((w) => (
                        <tr key={w.id}>
                          <td className="mono">{w.id}</td>
                          <td>{w.kind ?? 'standalone'}</td>
                          <td>{w.host ?? '—'}</td>
                          <td>{w.connected === false ? <span className="badge bad">reconnecting</span> : <span className="badge good">connected</span>}</td>
                          <td className="r">{w.activeVus}</td>
                          <td className="r">{w.concurrency}</td>
                          <td style={{ minWidth: 120 }}>
                            <div className="progress">
                              <div style={{ width: `${Math.min(100, (w.activeVus / Math.max(1, w.concurrency)) * 100)}%` }} />
                            </div>
                          </td>
                          <td className="muted">{Math.max(0, Math.round((Date.now() - w.ts) / 1000))}s ago</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              ) : (
                <div className="card-body">
                  <div className="callout warn">No workers are connected. Runs will wait in the queue until one starts.</div>
                </div>
              )}
            </Card>

            {data.mode === 'memory' ? (
              <Card title="Need more load than one machine?" hint="In-memory mode generates all load from this process. Switch to distributed mode to add worker machines.">
                <div className="stack" style={{ gap: 8 }}>
                  <div>
                    Raise the in-process limit: <code>LT_EMBEDDED_WORKER_CONCURRENCY=3000</code>
                  </div>
                  <div>
                    Or scale out: start RabbitMQ and Redis, then restart with <code>LT_MODE=distributed</code> and add workers with <code>npx lt worker</code>.
                  </div>
                </div>
              </Card>
            ) : (
            <Card title="Adding workers" hint="Workers are stateless and can run on any machine that reaches RabbitMQ, Redis and the application under test.">
              <div className="stack" style={{ gap: 8 }}>
                <div>
                  Node: <code>AMQP_URL=amqp://user:pass@mq-host:5672 REDIS_URL=redis://redis-host:6379 npx lt worker -c 200</code>
                </div>
                <div>
                  Docker: <code>docker compose up -d --scale worker=5</code>
                </div>
                {data.embeddedWorker && (
                  <div className="faint">
                    This server also runs an embedded worker ({data.embeddedWorker.concurrency} VUs). Disable it with <code>LT_EMBEDDED_WORKER=false</code> on dedicated controller hosts.
                  </div>
                )}
              </div>
            </Card>
            )}
          </div>
        )
      )}
    </div>
  );
}
